/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PlataformaAvRouteImport } from './routes/plataforma-av'
import { Route as MetodoAvRouteImport } from './routes/metodo-av'
import { Route as IaAvRouteImport } from './routes/ia-av'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as CasosDeUsoRouteImport } from './routes/casos-de-uso'
import { Route as AgendarDemonstracaoRouteImport } from './routes/agendar-demonstracao'
import { Route as IndexRouteImport } from './routes/index'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaAvRoute = PlataformaAvRouteImport.update({
  id: '/plataforma-av',
  path: '/plataforma-av',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoAvRoute = MetodoAvRouteImport.update({
  id: '/metodo-av',
  path: '/metodo-av',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAvRoute = IaAvRouteImport.update({
  id: '/ia-av',
  path: '/ia-av',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosDeUsoRoute = CasosDeUsoRouteImport.update({
  id: '/casos-de-uso',
  path: '/casos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarDemonstracaoRoute = AgendarDemonstracaoRouteImport.update({
  id: '/agendar-demonstracao',
  path: '/agendar-demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar-demonstracao': typeof AgendarDemonstracaoRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/conteudo': typeof ConteudoRoute
  '/ia-av': typeof IaAvRoute
  '/metodo-av': typeof MetodoAvRoute
  '/plataforma-av': typeof PlataformaAvRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar-demonstracao': typeof AgendarDemonstracaoRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/conteudo': typeof ConteudoRoute
  '/ia-av': typeof IaAvRoute
  '/metodo-av': typeof MetodoAvRoute
  '/plataforma-av': typeof PlataformaAvRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar-demonstracao': typeof AgendarDemonstracaoRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/conteudo': typeof ConteudoRoute
  '/ia-av': typeof IaAvRoute
  '/metodo-av': typeof MetodoAvRoute
  '/plataforma-av': typeof PlataformaAvRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar-demonstracao'
    | '/casos-de-uso'
    | '/conteudo'
    | '/ia-av'
    | '/metodo-av'
    | '/plataforma-av'
    | '/sobre'
    | '/solucoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar-demonstracao'
    | '/casos-de-uso'
    | '/conteudo'
    | '/ia-av'
    | '/metodo-av'
    | '/plataforma-av'
    | '/sobre'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/agendar-demonstracao'
    | '/casos-de-uso'
    | '/conteudo'
    | '/ia-av'
    | '/metodo-av'
    | '/plataforma-av'
    | '/sobre'
    | '/solucoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarDemonstracaoRoute: typeof AgendarDemonstracaoRoute
  CasosDeUsoRoute: typeof CasosDeUsoRoute
  ConteudoRoute: typeof ConteudoRoute
  IaAvRoute: typeof IaAvRoute
  MetodoAvRoute: typeof MetodoAvRoute
  PlataformaAvRoute: typeof PlataformaAvRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma-av': {
      id: '/plataforma-av'
      path: '/plataforma-av'
      fullPath: '/plataforma-av'
      preLoaderRoute: typeof PlataformaAvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo-av': {
      id: '/metodo-av'
      path: '/metodo-av'
      fullPath: '/metodo-av'
      preLoaderRoute: typeof MetodoAvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-av': {
      id: '/ia-av'
      path: '/ia-av'
      fullPath: '/ia-av'
      preLoaderRoute: typeof IaAvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-de-uso': {
      id: '/casos-de-uso'
      path: '/casos-de-uso'
      fullPath: '/casos-de-uso'
      preLoaderRoute: typeof CasosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar-demonstracao': {
      id: '/agendar-demonstracao'
      path: '/agendar-demonstracao'
      fullPath: '/agendar-demonstracao'
      preLoaderRoute: typeof AgendarDemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarDemonstracaoRoute: AgendarDemonstracaoRoute,
  CasosDeUsoRoute: CasosDeUsoRoute,
  ConteudoRoute: ConteudoRoute,
  IaAvRoute: IaAvRoute,
  MetodoAvRoute: MetodoAvRoute,
  PlataformaAvRoute: PlataformaAvRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
